### ISSUE TITLE
What is the license for the svg files?

### ISSUE THREAD

**Issue by helinwang** [dwyl/repo-badges#22]
I am interested in using the repo, but could not find what is the license of the files.

**Comment by nelsonic** [comment]
@helinwang _good question_ what License do you _need_ it to be?

**Comment by nelsonic** [comment]
@helinwang the License can be _anything_ you need it to be.
Closing this issue.
If anyone `else` has this question we can add a line to the readme to inform people they are 100% free to use the images for any purpose.
