### ISSUE TITLE
is hit count working?

### ISSUE THREAD

**Issue by spences10** [dwyl/repo-badges#24]
Hi thanks for this :+1:

I added the hit count badge to my repo, is it in working order?

![image](https://cloud.githubusercontent.com/assets/234708/25324080/8bc83d10-28bb-11e7-940f-cf28bc5e17cd.png)

[![HitCount](https://hitt.herokuapp.com/spences10/twitter-bot-bootstrap.svg)](https://github.com/spences10/twitter-bot-bootstrap)

**Comment by sohilpandya** [comment]
Thanks for raising the issue @spences10! We'll take a look into it 👍

**Comment by spences10** [comment]
@sohilpandya closing, this. Feel free to open your own issue to resolve it, I'm no longer interested in it being resolved
