### ISSUE TITLE
Documentation Badge for Private Repos

### ISSUE THREAD

**Issue by fresh5447** [dwyl/repo-badges#29]
Using this service, https://inch-ci.org/, my repo is not found. I am thinking it may be because it is a private repository.

Is there a service I should use to get a documentation badge for private repos?

**Comment by nelsonic** [comment]
@fresh5447 inch-ci is a great service. 
We don't tend to write "closed source" code (_AKA "private" repositories_) @dwyl so I cannot 
help clarify this for you ...

Perhaps the best person to ask would be it's creator @rrrene
or open an issue asking this on: https://github.com/inch-ci/inch_ci-web

**Comment by fresh5447** [comment]
Thanks for the clarification. I will reach out to them.
