### ISSUE TITLE
Remove bithound from docs as it seems to be not working

### ISSUE THREAD

**Issue by 92arpitgoyal** [dwyl/repo-badges#34]
Hi,

I was trying to integrate badges into my repo and found that bithound no more provides it's services and we should remove it from docs, I take this up if you want if wan to make these changes.

**Comment by nelsonic** [comment]
Agreed. If you have time to create a pull request, please remove. Thanks.

**Comment by 92arpitgoyal** [comment]
Thanks for the merge.

**Comment by iteles** [comment]
😢 
![image](https://user-images.githubusercontent.com/4185328/46946847-f4fdfa00-d070-11e8-8809-90804ae622f6.png)
