### ISSUE TITLE
Petty Description Update Request

### ISSUE THREAD

**Issue by jarrodwhitley** [dwyl/repo-badges#37]
I can't do a pull request for this so this is the only other way I know to mention this. If I'm just being ridiculous feel free to ignore me :)

Could you update the grammar in the repo description?

**Current:**
⭐️ use repo badges (build passing, coverage, etc) in your readme/markdown file to signal code "quality" in a project.

**Suggested:**
⭐️ Use repo badges (build passing, coverage, etc) in your readme/markdown file to signal code quality in a project.

**Comment by iteles** [comment]
:smile: No worries @jarrodwhitley, happy to change the description. 

Done! Please close the issue once you've checked.

**Comment by jarrodwhitley** [comment]
lol thank you for humoring me. Love your work.
