### ISSUE TITLE
l found a error!

### ISSUE THREAD

**Issue by SH0-ahacker** [dwyl/repo-badges#41]
guys !, i found an error **"Error 502 Ray ID: 562936080c57f1fb • 2020-02-09 22:17:01 UTC
Bad gateway "**, I found this error because I was trying to enter hits.dwyl.com and I found this error!

![image](https://user-images.githubusercontent.com/52937131/74111111-e5ad9480-4b70-11ea-821d-4830602328a5.png)

**Comment by nelsonic** [comment]
@SH0-ahacker thanks for reporting this. We are investigating on Cloudflare. 🔍

**Comment by cluzier** [comment]
Having this issue as well.

**Comment by SH0-ahacker** [comment]
^^

**Comment by nelsonic** [comment]
No longer an issue. Closing.
