### ISSUE TITLE
Some badges on the read me doesn't appear correctly

### ISSUE THREAD

**Issue by OudomMunint** [dwyl/repo-badges#50]
![image](https://github.com/dwyl/repo-badges/assets/108245473/a4cb1311-4bc0-45ea-bc04-6fb41399a141)

**Comment by nelsonic** [comment]
Related to: https://github.com/dwyl/technology-stack/issues/88 😢

**Comment by OudomMunint** [comment]
> Related to: [dwyl/technology-stack#88](https://github.com/dwyl/technology-stack/issues/88) 😢

🫡
