### ISSUE TITLE
Flat Badges?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/repo-badges#8]
Do People *Prefer* "*Flat*" Badges (*without a button shadow*)
e.g: [![Build Status](https://img.shields.io/travis/dwyl/time/master.svg?style=flat-square)](https://travis-ci.org/dwyl/time)

**Comment by iteles** [comment]
I'm a far of flat, but with slightly rounded corners.

**Comment by nelsonic** [comment]
Flat with rounded corner:
[![Build Status](https://img.shields.io/travis/dwyl/time/master.svg?style=flat)](https://travis-ci.org/dwyl/time)

**Comment by iteles** [comment]
:+1:

**Comment by nelsonic** [comment]
I think _flat_ is the `default` now (_so closing_) 😉
